version: '3'
services:
  mysql-service:
    image: mysql
    networks:
      - mysql-db-network
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=lojadodri
  web-service:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - mysql-db-network
    depends_on:
      - mysql-service
    restart: always
    deploy:
      resources:
        limits:
          memory: 700M
        reservations:
          memory: 700M
networks:
  mysql-db-network:
    driver: bridge
