version: '3'
services:

  mysql-service:
    image: mysql
    networks:
      - mysql-db-network
    environment:
      - MYSQL_ROOT_PASSWORD=codigo123
      - MYSQL_DATABASE=lojadodri
  web-service:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - mysql-db-network
    depends_on:
      - mysql-service
    restart: always
    deploy:
      resources:
        limits:
          memory: 700M
        reservations:
          memory: 700M

  flyway:
    image: flyway/flyway:latest
    volumes:
      - ./sql:/flyway/sql
    environment:
      - FLYWAY_URL=jdbc:mysql://mysql-service:3306/lojadodri
      - FLYWAY_USER=root
      - FLYWAY_PASSWORD=codigo123
      - FLYWAY_BASELINE_ON_MIGRATE=true
    depends_on:
      - mysql-service
    command: repair


networks:
  mysql-db-network:
    driver: bridge
